#!/usr/bin/env python3



import os
import sys

from analyzer import Analyzer
from termcolor import colored
import helpers

def main():
   
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets screen_name")
        
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    count=50
    tweets = helpers.get_user_timeline(sys.argv[1],count)
    
    
    if tweets is None:
        sys.exit("Error, unable to access user's tweets")
        
    positives ,negatives, neutrals =0.0, 0.0 ,0.0
    
    for tweet in tweets:
         score = analyzer.analyze(tweet)
         if score >0.0:
             positives += 1
             print(colored(int(score), "green"),colored(tweet, "green"))
         elif score < 0.0:
             negatives += 1
             print(colored(int(score), "red"), colored(tweet, "red"))
         else:
             neutrals += 1
             print(colored(int(score),"yellow"),colored(tweet, "yellow"))
             
   
   
   
if __name__ == "__main__":
    main()
         
        
        
        
        
        
        
        
        
        
        
        
        
    
        
